stages:
    - Build
    - Run

Build code:
    stage: Build
    script:
        - make
    artifacts:
        paths:
            - hello
        
Nominal Run:
    stage: Run
    script:
        - ./hello
