name: Hello Testing
# This workflow is triggered on pushes to the repository.
# jsut to test
on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: make
      - name: Nominal Run
        run: ./hello
      - uses: actions/upload-artifact@master
        with:
          name: hello-artifact
          path: hello

