name: Hello Testing
# This workflow is triggered on pushes to the repository.
# jsut to test
on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: |
            "hello/playbook.yml"
            "hello/playbook1.yml"
#           args: "hello/playbook.yml"
      - uses: actions/checkout@v1
      - name: Build Code
        run: make
      - name: Nominal Run
        run: ./hello
      - uses: actions/upload-artifact@master
        with:
          name: hello-artifact
          path: hello

